export enum PATHS {
  PUBLICK_NAVIGATION = 'PUBLICK_NAVIGATION',
  ONBORDING = 'ONBORDING',
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  APP_DRAWER = 'APP_DRAWER',
  TAB_NAVIGATOR = 'TAB_NAVIGATOR',
  DASHBOARD_TAB = 'DASHBOARD_TAB',
  ABOUT_TAB = 'ABOUT_TAB',
  CHAT_TAB = 'CHAT_TAB',
  CHAT = 'CHAT',
}
